apiVersion: "xbank/v1beta1"
kind: "Gateway"
metadata:
  name: "repo4"
  version: "v2"
  minorVersion: "0.0"
  teamName: "team"
spec:
  muhtar: "1.6.6"
  encumen: "1.2.3"
  contextPath: "/test"
  operations:
  - name: "zafer"
    description: "test"
    httpVerb: "POST"
    route: "/test"
    target:
      httpVerb: "GET"
      host: "test"
      timeoutInSeconds: 1233
      transformationHandledExceptionCodes:
      - 303
      - 307
      route:
        type: "header"
        value: "test"
    transformation:
      request:
        filepath: "/test/zafer/transformation/request.mjs"
        timeoutInMilliSeconds: 3000
      response:
        filepath: "/test/zafer/transformation/response.mjs"
        timeoutInMilliSeconds: 3000
    validation:
      request:
        filepath: "/test/zafer/validation/request.mjs"
      response:
        filepath: "/test/zafer/validation/response.mjs"
  transformationRepo:
    url: "https://github.com/zaferbozkurtsavana/apigw-repo4"
    tag: "v1.0.2"
